export const INFINITE_HORROR_STATUS_DEFINITIONS = Object.freeze([
  Object.freeze({
    id: 'status-spirit',
    name: '灵体',
    label: '灵体',
    description: '可穿越结构类碰撞，但不会绕过地图边界或其他未声明的阻挡。',
    icon: 'ghost',
    color: '#6f57a5',
    category: 'trait',
    scopes: Object.freeze(['actor', 'token']),
    maxStacks: 1,
    changes: Object.freeze([]),
    capabilities: Object.freeze({ collisionBypassGroups: Object.freeze(['structure']) }),
    builtIn: true,
  }),
  Object.freeze({
    id: 'status-rooted',
    name: '定身',
    label: '定身',
    description: '无法移动，但仍可进行交互与战斗行动。',
    icon: 'anchor',
    color: '#b96c24',
    category: 'debuff',
    scopes: Object.freeze(['actor', 'token']),
    maxStacks: 1,
    changes: Object.freeze([]),
    capabilities: Object.freeze({ canMove: false }),
    builtIn: true,
  }),
  Object.freeze({
    id: 'status-incapacitated',
    name: '失能',
    label: '失能',
    description: '无法移动、交互或进行战斗行动。',
    icon: 'circle-slash',
    color: '#a83f3f',
    category: 'debuff',
    scopes: Object.freeze(['actor', 'token']),
    maxStacks: 1,
    changes: Object.freeze([]),
    capabilities: Object.freeze({ canMove: false, canInteract: false, canActInCombat: false }),
    builtIn: true,
  }),
]);
